# Generated by Django 5.0.3 on 2024-03-07 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0.0)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
